name: stdlib
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  signals: ^7.1.0
  flutter_hooks: ^0.21.3+1
  lucide_icons_flutter: ^3.1.15

